/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }


//
//    Carsharing
//
//    Drive now:
//
//            1. Assume that you are registered already
//2. BMW price: 34 ct/Min
//3. Mini price: 31 ct/Min
//4. insurance: 1 for each ride
//5. Keep: 15 ct/Min
//6. Reservation for 8 hours - 10 ct/Min
//7. AIRPORT fee: 12
//
//    Packages:
//            1. 500 min (139.99) => 28 ct/min
//3 - 29, 80 km
//6 - 54, 120 km
//9 - 79, 200 km
//24 - 109, 200 km
//+ 29 ct/km
//
//
//    Input: distance (km), expected driving time (mins)
//
//    List<String> sharings = Arrays.toList("cartogo", "drivenow", "beezero");
//
//    psvm(String... args) {
//        if (args[0] == null || args[0].isDigit)
//            int dist = Integer.valueOf(args[0]);
//        int time = Integer.valueOf(args[1]);
//
//        int min = 1000;
//        String res;
//        for(String cs: sharings){
//            int pr = calculatePrise(cs, dist, time);
//            if (pr < min){
//                min = pr;
//                res = cs;
//            }
//        }
//        sout("The minimal price is %s in car-sharing %s", min, res);
//    }
//
//    private int calculatePrise(String cs, int dist, int time){
//        int basePrice = 28 * time + (dist > 200) ? (dist-200)*29 : 0;
//        int packagePrice =
//    }
}
